import fss from 'fs';

export class MarineProcessor {
  constructor (marineAddress) {
    this.balances = []
    this.principals = []
    this.marineAddress = marineAddress
    const data = fss.readFileSync('build/' + marineAddress + '.json', 'utf8')
    this.markets = JSON.parse(data)
  }

  run () {
    for (const key in this.markets) {
      const market = this.markets[key]
      this.balances.push(parseInt((Number(market.balance) / 1000).toString()))
      this.principals.push(parseInt(Number(Number(market.principal) / 1000).toString()))
    }

    let resultString = `//The code is generated by api/marine.js\nexport const balances: i64[] = ${JSON.stringify(this.balances)}\n`
    resultString += `export const principals: i64[] = ${JSON.stringify(this.principals)}\n`
    resultString += `export const address: string = ${JSON.stringify(this.marineAddress)}\n`

    fss.writeFileSync('src/static/marine.ts', resultString)
    console.log(this.marineAddress + ' processed')
  }
}

