//The code is generated by api/marine.js
export const balances: i64[] = [5145520854,0,0,0,0,0,0,0,0,177363610519630,0,0,0,0,1143168374563,0,24287618762811,0,0,0]
export const principals: i64[] = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
