//The code is generated by api/marine.js
export const balances: i64[] = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000000000000000000, 0,
    0, 0,
  ];
export const principals: i64[] = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 567107750472589, 0, 0,
    0, 0,
  ];
