//The code is generated by api/marine.js
export const balances: i64[] = [0,0,0,0,0,0,148346,0,0,0,0,6927885371,0,0,0,0,0,0,0,0]
export const principals: i64[] = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3520816338232545,0,0,0,0]
