//@ts-ignore
import { Bytes, Event } from "@hyperoracle/zkgraph-lib";
import { Judgment } from "./modules/judgment";

/**
 * The idea of Compound Liquidator Automation is to monitor three types of events, 
 * namely NewCloseFactor, NewCollateralFactor, and Sync, 
 * in order to calculate whether the current user can be liquidated.
 *
 * @param {Event[]} events - The list of Event objects to handle.
 * @return {Bytes} The generated Bytes object.
 */
export function handleEvents(events: Event[]): Bytes {
  return new Judgment(events).toBytes();
}
